export const medicalQualifications = [
  'Akupunktur',
  'Allergologie',
  'Allgemeine Chirurgie',
  'Allgemeinmedizin',
  'Altenpflegehelfer/in ',
  'Altenpfleger/in ',
  'Anästhesiologie',
  'Anatomie',
  'Andrologie',
  'Apotheker/in ',
  'Arbeitsmedizin',
  'Arzthelfer in Ausbildung ',
  'Ärztliches Qualitätsmanagement',
  'Augenheilkunde',
  'Balneologie und Medizinische Klimatologie',
  'Betriebsmedizin',
  'Biochemie',
  'Dermatopathologie',
  'Diabetologie',
  'Ergotherapeut/in ',
  'Ernährungsmedizin',
  'Flugmedizin',
  'Forensische Psychiatrie',
  'Gefäßchirurgie',
  'Geriatrie',
  'Gesundheits- und Kinderkrankenpfleger/in',
  'Gesundheits- und Krankenpflegehelfer/in',
  'Gesundheits- und Krankenpfleger/in',
  'Gynäkologie und Geburtshilfe',
  'Gynäkologische Endokrinologie und Reproduktionsmedizin',
  'Gynäkologische Exfoliativ-Zytologie',
  'Gynäkologische Onkologie',
  'Hals-Nasen-Ohrenheilkunde',
  'Hämostaseologie',
  'Handchirurgie',
  'Haut- und Geschlechtskrankheiten',
  'Hebamme/Entbindungspfleger ',
  'Heilpraktiker/in ',
  'Herzchirurgie',
  'Homöopathie',
  'Humangenetik',
  'Hygiene und Umweltmedizin',
  'Immunologie',
  'Infektiologie',
  'Infektionsepidemiologie',
  'Innere Medizin',
  'Innere Medizin und Angiologie',
  'Innere Medizin und Endokrinologie und Diabetologie',
  'Innere Medizin und Gastroenterologie',
  'Innere Medizin und Hämatologie und Onkologie',
  'Innere Medizin und Kardiologie',
  'Innere Medizin und Nephrologie',
  'Innere Medizin und Pneumologie',
  'Innere Medizin und Rheumatologie',
  'Intensivmedizin',
  'Kardiale Magnetresonanztomographie',
  'Kinder- und Jugend-Endokrinologie und -Diabetologie',
  'Kinder- und Jugend-Nephrologie',
  'Kinder- und Jugend-Orthopädie',
  'Kinder- und Jugend-Pneumologie',
  'Kinder- und Jugend-Rheumatologie',
  'Kinder- und Jugendmedizin',
  'Kinder- und Jugendpsychiatrie und -psychotherapie',
  'Kinder-Hämatologie und -Onkologie',
  'Kinder-Kardiologie',
  'Kinderchirurgie',
  'Kinderradiologie',
  'Klinische Akut- und Notfallmedizin',
  'Klinische Pharmakologie',
  'Krankenhaushygiene',
  'Laboratoriumsmedizin',
  'Logopäde/in ',
  'Magnetresonanztomographie fachgebunden',
  'Manuelle Medizin (Chirotherapie)',
  'Masseur/in ',
  'Medikamentöse Tumortherapie',
  'Medizin-Ingenieur ',
  'Medizinisch-technische Assistentin (MTA) ',
  'Medizinisch-technische Laboratoriumsassistentin (MTLA) ',
  'Medizinisch-technische Radiologieassistentin (MTRA) ',
  'Medizinische Fachangestellte',
  'Medizinische Informatik',
  'Medizinstudent/in ',
  'Medizintechnicker in Ausbildung ',
  'Medizintechniker/in ',
  'Mikrobiologie',
  'Mund-Kiefer-Gesichtschirurgie',
  'Naturheilverfahren',
  'Neonatologie',
  'Neurochirurgie',
  'Neurologie',
  'Neuropädiatrie',
  'Neuropathologie',
  'Neuroradiologie',
  'Notarzt ',
  'Notfallmedizin',
  'Notfallsanitäter',
  'Nuklearmedizin',
  'Nuklearmedizinische Diagnostik für Radiologen',
  'Öffentliches Gesundheitswesen',
  'Operationstechnischer Assistent/in',
  'Orthopädie und Unfallchirurgie',
  'Orthopädische Rheumatologie',
  'Pädiatrische Gastroenterologie',
  'Palliativmedizin',
  'Pathologie',
  'Pfleger in Ausbildung ',
  'Pharmakant ',
  'Pharmakologie',
  'Pharmakologie und Toxikologie',
  'Pharmazeuten in Ausbildung ',
  'Pharmazeutisch-kaufmännischer Angestellte/r (PKA)',
  'Pharmazeutisch-technischer Assistent/in (PTA) ',
  'Phlebologie',
  'Phoniatrie und Pädaudiologie',
  'Physikalische Therapie',
  'Physikalische und Rehabilitative Medizin',
  'Physiologie',
  'Plastische und Ästhetische Operationen',
  'Plastische, Rekonstruktive und Ästhetische Chirurgie',
  'Proktologie',
  'Psychiatrie und Psychotherapie',
  'Psychoanalyse',
  'Psychologen in Ausbildung ',
  'Psychosomatische Medizin und Psychotherapie',
  'Psychotherapie fachgebunden',
  'Radiologie',
  'Rechtsmedizin',
  'Rehabilitationswesen',
  'Rettungsassistent/in ',
  'Rettungsdienst in Ausbildung ',
  'Rettungshelfer ',
  'Rettungssanitäter/in ',
  'Röntgendiagnostik für Nuklearmediziner',
  'Schlafmedizin',
  'Sexualmedizin',
  'Sozialmedizin',
  'Spezielle Geburtshilfe und Perinatalmedizin',
  'Spezielle Kardiologie für EMAH',
  'Spezielle Kinder- und Jugendurologie',
  'Spezielle Orthopädische Chirurgie',
  'Spezielle Schmerztherapie',
  'Spezielle Unfallchirurgie',
  'Spezielle Viszeralchirurgie',
  'Sportmedizin',
  'Strahlentherapie',
  'Suchtmedizinische Grundversorgung',
  'Thoraxchirurgie',
  'Transfusionsmedizin',
  'Transplantationsmedizin',
  'Tropenmedizin',
  'Urologie',
  'Virologie',
  'Viszeralchirurgie'
];
